# Etapas do build
steps:

# ID: Identificador
# name: Comando de execução
## grc.io =  Url base de registro
## $PROJECT_ID = nome do projeto criado no GPC
## docker-compose = Imagem docekr a ser usada
## arqs = argumentos para docker-compose
- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

# Verificando os caontainers que estão ativos
- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

# Rodando composer
- id: "Rodando composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

# Copiando.env
- id: "Copiando .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

# Execuções laravel
- id: "Rodando key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando Migrations"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

- id: "Rodando phpunit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/php/phpunit', '-c', '/var/www/phpunit.xml']
